---
- name: Write registry IP to coreos servers
  shell: fleetctl ssh {{ item }} "if [ \$(grep {{ registry_host }} /etc/hosts | wc -l) -gt 0 ]; then sudo sed -i 's/.*{{ registry_host }}.*/{{ m_registry_host.results[0].IP }} {{ registry_host }}/g' /etc/hosts; else echo \"{{ m_registry_host.results[0].IP }} {{ registry_host }}\" | sudo tee --append /etc/hosts 1>/dev/null ;fi"
  with_items: m_registry_host.results[0].item.IDS

- name: Write registry IP locally
  shell: if [ $(grep {{ registry_host }} /etc/hosts | wc -l) -gt 0 ]; then sudo sed -i 's/.*{{ registry_host }}.*/{{ m_registry_host.results[0].IP }} {{ registry_host }}/g' /etc/hosts; else echo "{{ m_registry_host.results[0].IP }} {{ registry_host }}" | sudo tee --append /etc/hosts 1>/dev/null ;fi
